version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Build Application
          command: ./gradlew clean assembleDebug

jobs1:
  test:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    - run:
        name: Android Lint
        command: ./gradlew lintDebug
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
#jobs:
#  build-app:
#    working_directory: ~/code
#    docker:
#      - image:
#    environment:
#      JVM_OPTS: -Xmx3200m
#    steps:
#      - checkout
#      - restore_cache:
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Download Dependencies
#          command: ./gradlew androidDependencies
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Build Application
#          command: ./gradlew clean assembleDebug
#
#  test-app:
#    - run:
#        name: Android Lint
#        command: ./gradlew lintDebug
#
#  deploy-app:
#    - store_artifacts:
#        path: app/build/reports
#        destination: reports
#    - store_test_results:
#        path: app/build/test-results
#
#workflows:
#  version: 2
#  build-and-test-deploy:
#    jobs:
#      - build-app
#      - test-app
#      - deploy-app